#!/bin/bash

train_cmd='run.pl'
decode_cmd='run.pl'
nj=1
mfccdir='mfcc'

source ./path.sh

echo "Decoding..."
#utils/mkgraph.sh --mono data/lang exp/mono exp/mono/graph || exit 1
./mydecode.sh --config conf/decode.config --nj $nj --cmd "$decode_cmd" exp/mono/graph data/test exp/mono/decode


echo "Done"
