#!/bin/sh

. ./path.sh

train_cmd=run.pl
decode_cmd=run.pl
nj=4

echo
echo "===== Train SAT triphones ====="
echo
#steps/train_sat.sh  --cmd "$train_cmd" 2000 11000 data/train data/lang exp/tri2b_ali exp/tri3b || exit 1;
steps/train_sat.sh  --cmd "$train_cmd" 4200 40000 data/train data/lang exp/tri2b_ali exp/tri3b || exit 1;

echo
echo "===== SAT DECODING ====="
echo
utils/mkgraph.sh data/lang exp/tri3b exp/tri3b/graph || exit 1
steps/decode_fmllr.sh --config conf/decode.config --nj $nj --cmd "$decode_cmd" exp/tri3b/graph data/test exp/tri3b/decode
echo
echo "===== run.sh script is finished ====="
echo
